#mysql_test:mysql_test.c
#	gcc mysql_test.c -o mysql_test -I/usr/include/ -L/usr/lib/x86_64-linux-gnu/ -lmysqlclient
#mysql_test2:mysql_test2.c
#	gcc mysql_test2.c -o mysql_test2 -I/usr/include/ -L/usr/lib/x86_64-linux-gnu/ -lmysqlclient
mysql_test3:mysql_test3.c
	gcc mysql_test3.c -o mysql_test3 -I/usr/include/ -L/usr/lib/x86_64-linux-gnu/ -lmysqlclient
clean:
	rm mysql_test mysql_test2 mysql_test3
